title: pcjdev.github.io
author: pcjdev
description: >
  The personal blog of a software engineer passionate about programming,
  clean code, security and open source.

show_excerpts: false

minima:
  date_format: "%Y-%m-%d"
  social_links:
    twitter: pcjdev
    github:  pcjdev
    rss:  rss

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
